Require Import LL.PLL.Tactics.
Set Implicit Arguments.

Section InvRules.
   
Lemma invertibility_bot : forall n B M, LL2N n B  (Bot::M) -> LL2S B  M.
Proof with sauto.
  induction n ;intros...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop x.
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop x.
    + checkPermutationCases H1.
        LLleft F G x.
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLright F G x.
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLwith F G x.
        1-2: eapply IHn. 
        1-2: rewrite perm_swap. 1-2: rewrite <- H1...
    + checkPermutationCases H1.
        rewrite H4... apply LL2NtoLL2S in H2...
        rewrite H3. rewrite <- H1. apply LL2NtoLL2S in H2...
    + checkPermutationCases H1.
        LLpar F G x.
        eapply IHn.
        eapply LL2N_compat with (B1:=B) (L1:=  F :: G ::⊥ :: x)... 
        rewrite <- H1...
   + checkPermutationCases H1.
       checkPermutationCases H1.
        LLtensor F G x0 N .
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
        apply LL2NtoLL2S in H3...
        LLtensor F G M0 x0 .
        apply LL2NtoLL2S in H2... 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
   + checkPermutationCases H1.
        LLstore F x.
        eapply IHn. rewrite <- H1...
   + LLcopy F.
        eapply IHn. 
        rewrite perm_swap... 
Qed.

Lemma invertibility_par : forall n B M F G, 
                            LL2N n B  (F ⅋ G::M) -> LL2S B  (F::G::M).
Proof with sauto.
  induction n ;intros...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (F::G::x). rewrite H2...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (F::G::x). rewrite H2...
    + checkPermutationCases H1.
        LLleft F0 G0 (F::G::x). rewrite H3...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::F0 :: x)... 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLright F0 G0 (F::G::x). rewrite H3...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::G0 :: x)... 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLwith F0 G0 (F::G::x). rewrite H4...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::F0 :: x)... 
        2: eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::G0 :: x)... 
        1-2: eapply IHn. 
        1-2: rewrite perm_swap. 1-2: rewrite <- H1...
    + checkPermutationCases H1.
        LLbot (F::G::x). rewrite H3...
        eapply IHn. rewrite <- H1... 
    + checkPermutationCases H1.
       { inversion H3...
          rewrite H4.  
           apply LL2NtoLL2S in H2... }
       { LLpar F0 G0 (F::G::x). rewrite H3...
          eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::F0 :: G0::x)... 
          eapply IHn. 
          eapply LL2N_compat with (B1:=B) (L1:=F0 :: G0::(F ⅋ G) ::x)... 
            rewrite <- H1... }
   + checkPermutationCases H1.
       checkPermutationCases H1.
        LLtensor F0 G0 (F::G::x0) N . rewrite H4... rewrite <- H5...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::F0 ::x0)... 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
        apply LL2NtoLL2S in H3...
        LLtensor F0 G0 M0 (F::G::x0) . rewrite H4... rewrite <- H5...
        apply LL2NtoLL2S in H2...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::G0 ::x0)... 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
   + checkPermutationCases H1.
        LLstore F0 (F::G::x). rewrite H3...
        eapply IHn. rewrite <- H1...
   + LLcopy F0.
        eapply LL2S_compat with (B1:=B) (L1:=  F :: G ::F0 ::M)... 
        eapply IHn.
        rewrite perm_swap... 
Qed.

Lemma invertibility_store : forall n B M F,
                            LL2N n B  (? F::M) -> LL2S (F::B)  M.
Proof with sauto.
  induction n ;intros...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop x.
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop x. 
    + checkPermutationCases H1.
        LLleft F0 G x. 
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLright F0 G x.  
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLwith F0 G x.  
        1-2: eapply IHn. 
        1-2: rewrite perm_swap. 1-2: rewrite <- H1...
    + checkPermutationCases H1.
        LLbot x. 
        eapply IHn. rewrite <- H1... 
    + checkPermutationCases H1.
        LLpar F0 G x.  
          eapply IHn. 
          eapply LL2N_compat with (B1:=B) (L1:=F0 :: G:: ? F::x)... 
            rewrite <- H1... 
   + checkPermutationCases H1.
       checkPermutationCases H1.
        LLtensor F0 G x0 N .  
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
        apply LL2NtoLL2S in H3...
        apply LL2weakening...
        LLtensor F0 G M0 x0 . 
        apply LL2NtoLL2S in H2...
        apply LL2weakening...
        eapply IHn. 
        rewrite perm_swap. rewrite <- H1...
   + checkPermutationCases H1.
       { inversion H3...
          rewrite H4.  
           apply LL2NtoLL2S in H2... }
       { LLstore F0 x.
         rewrite perm_swap. 
          eapply IHn. 
            rewrite <- H1... }
    + LLcopy F0...
        eapply IHn.
        rewrite perm_swap... 
Qed.
   
Lemma invertibility_with : forall n B M F G, 
     LL2N n B (F & G::M) -> LL2S B (F::M) /\ LL2S B (G::M).
Proof with sauto.
  induction n ;intros...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (F::x). rewrite H2...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (G::x). rewrite H2...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (F::x). rewrite H2...
    + checkPermutationCases H1.
        LLleft F0 G0 (F::x). rewrite H3...
        rewrite perm_swap.
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLright F0 G0 (F::x). rewrite H3...
        rewrite perm_swap.
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
       { inversion H4...
          rewrite H5.  
           apply LL2NtoLL2S in H2... }
       { LLwith F0 G0 (F::x). rewrite H4...
         rewrite perm_swap.
         eapply IHn with (F:=F) (G:=G). 
         rewrite perm_swap. rewrite <- H1...
         rewrite perm_swap.
         eapply IHn with (F:=F) (G:=G). 
         rewrite perm_swap. rewrite <- H1... }
    + checkPermutationCases H1.
        LLbot (F::x). rewrite H3...
        eapply IHn with (F:=F) (G:=G). 
         rewrite <- H1... 
    + checkPermutationCases H1.
       LLpar F0 G0 (F::x). rewrite H3...
        eapply LL2S_compat with (B1:=B) (L1:=  F :: F0 :: G0::x)... 
        eapply IHn with (F:=F) (G:=G). 
          eapply LL2N_compat with (B1:=B) (L1:=F0 :: G0::(F & G) ::x)... 
            rewrite <- H1... 
   + checkPermutationCases H1.
       checkPermutationCases H1.
        LLtensor F0 G0 (F::x0) N . rewrite H4... rewrite <- H5...
        rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
        apply LL2NtoLL2S in H3...
        LLtensor F0 G0 M0 (F::x0) . rewrite H4... rewrite <- H5...
        apply LL2NtoLL2S in H2...
        rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
   + checkPermutationCases H1.
        LLstore F0 (F::x). rewrite H3...
        eapply IHn with (F:=F) (G:=G). 
        rewrite <- H1...
   + LLcopy F0.
      rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G).
        rewrite perm_swap...
   - inversion H...
    + checkPermutationCases H0.
    + checkPermutationCases H0.
        LLtop (G::x). rewrite H2...
    + checkPermutationCases H1.
        LLleft F0 G0 (G::x). rewrite H3...
        rewrite perm_swap.
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
        LLright F0 G0 (G::x). rewrite H3...
        rewrite perm_swap.
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
    + checkPermutationCases H1.
       { inversion H4...
          rewrite H5.  
           apply LL2NtoLL2S in H3... }
       { LLwith F0 G0 (G::x). rewrite H4...
         rewrite perm_swap.
         eapply IHn with (F:=F) (G:=G). 
         rewrite perm_swap. rewrite <- H1...
         rewrite perm_swap.
         eapply IHn with (F:=F) (G:=G). 
         rewrite perm_swap. rewrite <- H1... }
    + checkPermutationCases H1.
        LLbot (G::x). rewrite H3...
        eapply IHn with (F:=F) (G:=G). 
         rewrite <- H1... 
    + checkPermutationCases H1.
       LLpar F0 G0 (G::x). rewrite H3...
        eapply LL2S_compat with (B1:=B) (L1:=  G :: F0 :: G0::x)... 
        eapply IHn with (F:=F) (G:=G). 
          eapply LL2N_compat with (B1:=B) (L1:=F0 :: G0::(F & G) ::x)... 
            rewrite <- H1... 
   + checkPermutationCases H1.
       checkPermutationCases H1.
        LLtensor F0 G0 (G::x0) N . rewrite H4... rewrite <- H5...
        rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
        apply LL2NtoLL2S in H3...
        LLtensor F0 G0 M0 (G::x0) . rewrite H4... rewrite <- H5...
        apply LL2NtoLL2S in H2...
        rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G). 
        rewrite perm_swap. rewrite <- H1...
   + checkPermutationCases H1.
        LLstore F0 (G::x). rewrite H3...
        eapply IHn with (F:=F) (G:=G). 
        rewrite <- H1...
   + LLcopy F0.
      rewrite perm_swap.  
        eapply IHn with (F:=F) (G:=G).
        rewrite perm_swap...
Qed.

Lemma invertibility_bang : forall n B F, 
     LL2N n B [! F] -> LL2S B [F].
Proof with sauto.
  induction n ;intros...
   - inversion H...
   - inversion H...
    + apply LL2NtoLL2S in H3...
    + eapply IHn. 
Abort.

End InvRules.
